"""create_initial_schema

Revision ID: 69ae39eab224
Revises: 
Create Date: 2026-05-02 22:45:23.474325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ae39eab224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('bse_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.Enum('it', 'banking', 'finance', 'fmcg', 'auto', 'pharma', 'cement', 'energy', 'infrastructure', 'consumer', 'other', name='sector', schema='sentinel'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bse_code'),
    schema='sentinel'
    )
    op.create_index(op.f('ix_sentinel_companies_ticker'), 'companies', ['ticker'], unique=True, schema='sentinel')
    op.create_table('filings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_type', sa.Enum('annual_report', 'quarterly_results', 'earnings_transcript', name='filingtype', schema='sentinel'), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['sentinel.companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sentinel'
    )
    op.create_index(op.f('ix_sentinel_filings_company_id'), 'filings', ['company_id'], unique=False, schema='sentinel')
    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['sentinel.filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id'),
    schema='sentinel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_documents', schema='sentinel')
    op.drop_index(op.f('ix_sentinel_filings_company_id'), table_name='filings', schema='sentinel')
    op.drop_table('filings', schema='sentinel')
    op.drop_index(op.f('ix_sentinel_companies_ticker'), table_name='companies', schema='sentinel')
    op.drop_table('companies', schema='sentinel')
    # ### end Alembic commands ###
